### ISSUE TITLE
message组件没有绑定按钮点击事件？

### ISSUE THREAD

**Issue by luweiCN** [youngluo/mp-weui#10]
# [问题简单描述]

**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by blackjack0v0** [comment]
...我也看到了 ，作者没更新只能自己鲁一个了

**Comment by youngluo** [comment]
已解决 https://github.com/youngluo/mp-weui/releases/tag/v1.0.4
