### ISSUE TITLE
组件支持h5不？

### ISSUE THREAD

**Issue by zhongku** [youngluo/mp-weui#11]
您好,您的UI组件支持h5不？

**Comment by youngluo** [comment]
目前不支持

**Comment by zhongku** [comment]
我们现在公司想让我们用一套vue代码，同时支持小程序和h5？有什么好的建议不？

**Comment by youngluo** [comment]
用 mpvue 就行了啊，至于 UI 组件可能要自己封装了

**Comment by zhongku** [comment]
谢谢，现在正在尝试中，遇到了很多的问题，在前期打包的时候。有时间帮我们处理些纯技术问题吗？我们可以付费的

**Comment by youngluo** [comment]
额。。。这个得看具体情况了

**Comment by zhongku** [comment]
可以加QQ联系沟通下，具体的情况不？我的QQ号码2839018
