### ISSUE TITLE
这个怎么解决

### ISSUE THREAD

**Issue by QTTQ** [youngluo/mp-weui#4]
ERROR  Failed to compile with 1 errors                                                                                     09:13:16
This dependency was not found:

* !!../../../extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../../mpvue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-1a5ff368","scoped":false,"hasInlineConfig":false}!px2rpx-loader?{"baseDpr":1,"rpxUnit":0.5}!postcss-loader?{"sourceMap":true}!less-loader?{"sourceMap":false}!../../../mpvue-loader/lib/selector?type=styles&index=0!./index.vue in ./~/mp-weui/packages/radio/index.vue

**Comment by haigendong** [comment]
我也碰到了，使用的mpvue^1.0.10
`* !!../../../node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../../node_modules/mpvue-loader/l
ib/style-compiler/index?{"vue":true,"id":"data-v-0be8b893","scoped":false,"hasInlineConfig":false}!px2rpx-loader?{"baseDpr":1,"rpxUnit":0.5}!postcss-loader?{"sourceMap":true}!less-loader?{"s
ourceMap":false}!../../../node_modules/mpvue-loader/lib/selector?type=styles&index=0!./index.vue in ./src/pages/index/index.vue`

**Comment by youngluo** [comment]
我这边暂未出现类似问题，能否提供更详细的信息？

**Comment by haigendong** [comment]
![报错信息](https://ws2.sinaimg.cn/large/006tKfTcgy1fqzemwrcfoj30zu1iqk2y.jpg)
![报错信息](https://ws3.sinaimg.cn/large/006tKfTcgy1fqzekd17jgj31kw08p3zs.jpg)
![报错信息](https://ws1.sinaimg.cn/large/006tKfTcgy1fqzekmtxt2j31kw0uvh5r.jpg)

**Comment by youngluo** [comment]
@MagnifierSun 
![image](https://user-images.githubusercontent.com/7480381/39620257-187f6020-4fbd-11e8-8ac6-2e7c037b28da.png)

你把.vue后缀名加上试试

**Comment by ranwawa** [comment]
这是mpvue默认没有安装css-loader和node-sass导致的
