### ISSUE TITLE
npm下载的包里没有tabbar

### ISSUE THREAD

**Issue by ranwawa** [youngluo/mp-weui#5]
如题~~~网络原因传不了图

在文档里面也没有

但是在github上你的readme里面是说有的

**Comment by youngluo** [comment]
[tabbar通过设置app.json来实现,详情请看小程序文档](https://github.com/youngluo/mp-weui/blob/master/src/pages/tabbar/index.vue)

**Comment by ranwawa** [comment]
没打算自己造一个?这样可以跨小程序和H5呀
