### ISSUE TITLE
使用Dialog 时，设置 showCancel：false 为什么不起作用呢？

### ISSUE THREAD

**Issue by hapyli** [youngluo/mp-weui#8]
代码如下：
Dialog.confirm(res.data.msg, {
              showCancel: false,
              confirmColor: '#ff0000'
            })

**Comment by youngluo** [comment]
confirm showCancel 参数恒为true，建议使用这种方式：
![image](https://user-images.githubusercontent.com/7480381/40460660-6e554af0-5f3a-11e8-8f23-0c9938445fa6.png)
